language: python

python:
  - 2.7
  - 3.5

sudo: true

services:
  - docker

before_install:
  - pwd
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      export DOCKER_ENV=/opt/conda;
    else
      export DOCKER_ENV=/opt/conda/envs/py2;
    fi
  - pushd ../
  - git clone https://github.com/danielfrg/cyavro.git
  - popd
  - docker build -t cyhdfs3 .
  - docker build -t cyhdfs3.hdfs -f Dockerfile.hdfs .
  - docker run -it -p 8020:8020 -p 50070:50070 -v $(pwd):/cyhdfs3 -v $(pwd)/../cyavro:/cyavro cyhdfs3.hdfs
  - export CONTAINER_ID=$(docker ps -l -q)
  - sleep 60  # Wait for namenode and datanode

install:
  - pwd
  - echo $DOCKER_ENV
  - docker exec -it $CONTAINER_ID $DOCKER_ENV/bin/pip install -e /cyavro
  - docker exec -it $CONTAINER_ID $DOCKER_ENV/bin/python setup.py install

script:
  - pwd
  - docker exec -it $CONTAINER_ID $DOCKER_ENV/bin/py.test cyhdfs3 -s -vv
